### ISSUE TITLE
Columbus not included in the time zone drop down

### ISSUE THREAD

**Issue by chutch1994** [qubbit/argonaut#1]
When you go to edit your profile, Columbus isn't in the drop down for selected times. You can accomplish the same task by just putting in New York, but I feel like it should be in there.

**Comment by qubbit** [comment]
The small subset of time zones used by the app are from the tz database: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones 

Unfortunately, Columbus is not on the list.  `ls /usr/share/zoneinfo/America | grep Columbus` :(
