### ISSUE TITLE
Add confirm or undo button for removing reservations

### ISSUE THREAD

**Issue by abaird** [qubbit/argonaut#10]
As an admin, I have the ability to remove everyone's reservations. This is nice, but if I accidentally click on a reservation from someone else, there's no way to get it back. In order to prevent accidental deletions when you are logged in as admin (or non admin for that matter), it would be nice to have a confirmation dialog or a way to undo a reservation removal.

**Comment by qubbit** [comment]
Fixed by commit https://github.com/qubbit/argonaut-ui/pull/8/commits/012f282be4ce2ce3e7653282be42947dcef71d60

The PR is unmerged but the code is deployed to production.
