### ISSUE TITLE
you can reserve an app in a team you haven't joined (even when you are non-admin)

### ISSUE THREAD

**Issue by abaird** [qubbit/argonaut#8]
To reproduce:
1) as an admin, set up a few teams with valid apps and environments
2) note down the URL of some of those teams
3) logout as admin and login as non-admin
4) as a non-admin user, enter the URL of the team you created in step 2
5) attempt to reserve a non-reserved environment
expected: you should not be able to reserve apps on teams you haven't joined
actual: you are able to reserve apps on teams you have not joined (but know the url to)

**Comment by qubbit** [comment]
Fixed in the new version: v2.

Gracias!
